name: Daily Telegram Sender

on:
  schedule:
    - cron: "30 04 * * *"
    - cron: "30 15 * * *"

  workflow_dispatch:

jobs:
  send:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install packages
        run: |
          pip install -r requirements.txt

      - name: Morning
        if: github.event.schedule == '30 04 * * *'
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          MODE: morning
        run: python main.py

      - name: Evening
        if: github.event.schedule == '30 15 * * *'
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          MODE: evening
        run: python main.py

      - name: Manual
        if: github.event_name == 'workflow_dispatch'
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          MODE: morning
        run: python main.py
